title: "Citrix Developer"
email: "developer.citrix.com"
twitter_username: "citrixdeveloper"
github_username:  "citrixdeveloper"

collections:
  categories:

  sass:
    load_paths:
        - _sass
        - components