title: "Citrix Developer"
email: "developer.citrix.com"
twitter_username: "citrixdeveloper"
github_username:  "citrixdeveloper"

collections:
  categories:
  pages:
    output: true
  sass:
    load_paths:
        - _sass
        - components

