title: "Citrix Developer"
email: "developer.citrix.com"
twitter_username: "citrixdeveloper"
github_username:  "citrixdeveloper"
youtube_url: "https://www.youtube.com/channel/UCiOupk9QF6jdk3EDKTHDykA"
googleanalytics:

collections:
  categories:
  sdks:
  pages:
    output: true
  sass:
    load_paths:
        - _sass
        - components
        
exclude: ["gulpfile.js","package.json","yarn.lock","node_modules"]
